name: Upload Website using AWS S3 Bucket blue/green deployment

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Select deployment target (blue or green)'
        required: true
        default: 'blue'
        type: choice
        options:
          - blue
          - green
   

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: NodeJs Setup
      uses: actions/setup-node@v4
      with:
        node-version: ${{secrets.NODE_VERSION}}
    - name: Install Dependencies
      run: npm install
    - name: Build Project
      run: npm run build

    - name: configure AWS Credentials and Upload to S3
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-west-1'   # optional1: defaults to us-east-1
    - name: Deploy to S3
      run: | 
        if[
        "${{github.event.input.target}}"="green"];
        then aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_BLUE }} --delete;
        else aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_GREEN }} --delete;
        fi
        
      
      # aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET }} --delete